SELECT dicd.ICD9_CODE, dicdd.SHORT_TITLE, COUNT(*) as cnt
FROM DIAGNOSES_ICD dicd JOIN D_ICD_DIAGNOSES dicdd ON dicd.ICD9_CODE=dicdd.ICD9_CODE
GROUP BY dicd.ICD9_CODE, dicdd.SHORT_TITLE
ORDER BY cnt DESC
LIMIT 1;