SELECT * FROM (
SELECT ETHNICITY, COUNT(*) as cnt, COUNT(*) / (SELECT COUNT(*) FROM ADMISSIONS) as pctg, 'Overall' as typ
FROM ADMISSIONS
GROUP BY ETHNICITY
UNION ALL 
SELECT a.ETHNICITY, COUNT(*) as cnt, COUNT(*) / (SELECT COUNT(*) FROM ADMISSIONS a JOIN DIAGNOSES_ICD d ON a.SUBJECT_ID=d.SUBJECT_ID WHERE d.ICD9_CODE=4019) as pctg,
       'Hypertension' as typ
FROM DIAGNOSES_ICD d JOIN ADMISSIONS a ON d.SUBJECT_ID=a.SUBJECT_ID 
WHERE d.ICD9_CODE=4019
GROUP BY a.ETHNICITY
) t
WHERE t.pctg > 0.005
ORDER BY t.ETHNICITY, t.typ