SELECT a.ADMISSION_TYPE, (COUNT(*) / t.tot) as pctg
FROM 
    DIAGNOSES_ICD d 
JOIN 
    ADMISSIONS a ON d.SUBJECT_ID=a.SUBJECT_ID
JOIN
    (SELECT COUNT(ADMISSION_TYPE) as tot
    FROM DIAGNOSES_ICD d JOIN ADMISSIONS a ON d.SUBJECT_ID=a.SUBJECT_ID
    WHERE d.ICD9_CODE=4019) t
WHERE d.ICD9_CODE=4019
GROUP BY a.ADMISSION_TYPE, t.tot